### ISSUE TITLE
Can't send a private message

### ISSUE THREAD

**Issue by Evgura** [e107inc/e107#3550]
Stopped sending private messages on the site. Why is it that I'm the main administrator can't send a message?

![default](https://user-images.githubusercontent.com/25720089/48297462-75761600-e4ca-11e8-9adf-5f467909e69d.png)

**Comment by Moc** [comment]
Did this happen suddenly? 
What are your settings in the PM plugin admin area?

**Comment by Jimmi08** [comment]
I noticed this on e107.sk and update is sometimes when 2.2.0 was out (but not latest github).  I just haven't time to look at it. Mainadmin has problem on forum too, there is already issue about this.

**Comment by Evgura** [comment]
The problem was on three sites, I don't think it was an accident. Version 2.1.9 on two sites and 2.2.0 on another.
Overwritten the plugin files from here and it worked.
https://github.com/e107-ru/e107-ru

**Comment by Moc** [comment]
I have a feeling there's something weird going on with the userclass permissions. The forum seems to have permissions as well.

**Comment by CaMer0n** [comment]
Bit of a mystery. The last real changes to PM happened in January 2018.

**Comment by Jimmi08** [comment]
Admin works. Only Frontend:
![image](https://user-images.githubusercontent.com/5429548/48305096-f2ce7480-e524-11e8-9a2f-3b137d47c44a.png)

**Comment by Moc** [comment]
@Evgura What's your PHP version?

**Comment by Evgura** [comment]
@Moc Version PHP 7.0

**Comment by Moc** [comment]
I suspect there's a PHP 7.x incompatibility issue. Will look into it asap.

**Comment by CaMer0n** [comment]
@Jimmi08 Instead of using `print_a()`, try using `var_dump()` .

**Comment by Evgura** [comment]
Updated today with Github and again the problem with personal messages.
PHP version-7.1.24

"System Information
You are not allowed to send PMs to: Maxim"


![](https://user-images.githubusercontent.com/25720089/48297462-75761600-e4ca-11e8-9adf-5f467909e69d.png)

**Comment by Moc** [comment]
@Evgura Yes, no fix has been committed yet.

**Comment by Evgura** [comment]
PHP:  5.6 Private Message work normally.

**Comment by Moc** [comment]
Trying to reproduce this on PHP 7.1, but no luck yet. Clean install of e107, and clean install of the PM plugin. What are your settings here?: 

![image](https://user-images.githubusercontent.com/577978/49015399-4a0a5100-f183-11e8-8e38-56204656cd13.png)

**Comment by Evgura** [comment]
Yes, such settings.

**Comment by Moc** [comment]
Are the settings the same on your installation?

**Comment by Moc** [comment]
I do agree that there is an issue, I am just trying to figure out what is causing the issue :) 
Are your settings the same as I posted in the screenshot?

**Comment by Evgura** [comment]
I tried different settings. And as in the screenshot too.

**Comment by Jimmi08** [comment]
`var_dump(USERCLASS);`

`string(0) ""`

**Comment by Moc** [comment]
Please update from Github. You may need to reinstall the PM plugin (if you haven't used the PM system before, I recommend that), or at least delete the preferences and let the update routine do its work to restore the correct preferences.

**Comment by Evgura** [comment]
@Moc It's not working.

**Comment by Moc** [comment]
Did you reinstall the plugin? Or delete the preferences?

**Comment by Evgura** [comment]
I just updated it through Github.
OK, now I'll try to do as you say.

**Comment by Moc** [comment]
Is it possible to provide a website login and FTP access to your website? I cannot reproduce this at all so we'll need to debug this manually. 

If yes, please contact me or Cameron on Gitter.

**Comment by Evgura** [comment]
Posted for Tijn Kuyper on Gitter

**Comment by Evgura** [comment]
@Moc I have 4 site on E107 and on all 4 there is this problem with private messages.

**Comment by Moc** [comment]
@Evgura I understand and I'm trying to help you fix it. I don't understand what's wrong yet. I have asked you a question in Gitter. Please check :)

**Comment by SimSync** [comment]
@Evgura Do you have PDO activated? If not, please activate PDO and try again.
Check the e107_config.php and add `define('e_PDO', true);` to that file.

**Comment by Evgura** [comment]
The situation is, download the folder with the plugin (PM) from [this repository](https://github.com/e107-ru/e107-ru/tree/master/e107_plugins/pm) and copy to replace your site. Everything works without dancing with a tambourine. Pour it into your repository and that's it.

**Comment by SimSync** [comment]
The situation is, that the old mysql_* commands (which still work with php5.6) are deprecated and removed from php starting with php 7.0. 
If PDO is disabled on you systems, this can cause strange behaviors, like not working db queries or unforseen results.
I'm not sure, if this is really the cause for your issue, because i'm not able to reproduce this issue in any way. But at least it's a possibility that your system has PDO disabled and this would explain it a bit.
And by the way, e107org/e107 is open to pull requests. If e107-ru fixed an issue, a pull request from his/her side is more than welcome. 😏

**Comment by Moc** [comment]
@Evgura the code in that repository simply comments out code to avoid the error. That's not solving it, that's simply trying to bandaid things together and hope they work. 

Also, please try the suggestion by @SimSync, his reasoning makes sense

**Comment by Moc** [comment]
@Evgura Are all 4 sites hosted at the same hosting provider?

**Comment by Evgura** [comment]
@SimSync PDO is activated in PHP settings on the server.
@Moc you have access to the site, try it.

**Comment by Evgura** [comment]
@Moc Yes, have one but on different servers.

**Comment by Evgura** [comment]
@Moc Gave access to the cPanel control panel on the Gitter

**Comment by Jimmi08** [comment]
For me this was fixed with latest sync and reinstall PM plugin.  Now it works with 7.1.25

**Comment by SimSync** [comment]
@Evgura Are you able to implement a small change to one of the sourcefiles?

File: pm.php Line: 601 Change from:
`if(e107::getDb()->update('private_msg_block', "pm_block_count=pm_block_count+1 WHERE pm_block_from = '" . USERID . "' AND pm_block_to = '{$to_info['user_id']}'"))`

To:
`if(false !== e107::getDb()->update('private_msg_block', "pm_block_count=pm_block_count+1 WHERE pm_block_from = '" . USERID . "' AND pm_block_to = '{$to_info['user_id']}'"))`

To be clear: the `false !== ` before the `e107::getDb()->update` is the change ...

**Comment by Evgura** [comment]
@SimSync 
Moc has access to the site and the files, so he can try to avoid confusion.

**Comment by Evgura** [comment]
@Jimmi08 I tried reinstalling the PM plugin but it did not solve the problem.

**Comment by Moc** [comment]
Just an update, not a complete fix yet. With the help of @SimSync we have identified the issue but are still looking into the best way to fix it. Updates will follow. 

Tech info for future reference:
` the db_query returns an object instead of the number of modified records. Maybe this is the issue with the php version. Because the result from the update is not true or false or an int, it's an object and therefore fails the comparison in the if clause...`

**Comment by SimSync** [comment]
Probably fixed with PR #3665

**Comment by Moc** [comment]
@Evgura If you update your websites with the latest files from Github, it should be resolved. You can also get the latest e107_handlers/mysql_class.php file (that's the only one changed to fix this issue).

**Comment by Evgura** [comment]
I understand, thank you.

**Comment by Moc** [comment]
@Evgura Did you happen to have a chance to test this?

**Comment by Evgura** [comment]
@Moc Updated with Github, everything works. Private messages are sent.

**Comment by Moc** [comment]
Great! Closing the issue then :) 👍
